name: Build IPQ60xx
on: [push]

jobs:
    build:
        name: Prepare and build IPQ60xx images
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Update and install feeds
              run: |
                ./scripts/feeds update -a
                ./scripts/feeds install -a

            - name: Generate config for IPQ60xx Generic
              run: |
                #echo "CONFIG_TARGET_ipq60xx=y" > .config
                #echo "CONFIG_TARGET_ipq60xx_generic=y\n" >> .config
                #echo "CONFIG_TARGET_MULTI_PROFILE=y\n" >> .config
                #echo "CONFIG_TARGET_ALL_PROFILES=y\n" >> .config
                #echo "CONFIG_TARGET_PER_DEVICE_ROOTFS=y\n" >> .config
                #echo "CONFIG_TARGET_ROOTFS_INITRAMFS=y\n" >> .config
                #echo "CONFIG_TARGET_INITRAMFS_COMPRESSION_ZSTD=y\n" >> .config
                #echo "CONFIG_PACKAGE_luci=y\n" >> .config
                #echo "CONFIG_PACKAGE_wpad-basic-wolfssl=m\n" >> .config
                #echo "CONFIG_PACKAGE_wpad-wolfssl=y\n" >> .config
                #echo "CONFIG_PACKAGE_libwolfssl=n\n" >> .config
                #echo "CONFIG_PACKAGE_libwolfssl-cpu-crypto=y\n" >> .config
                cp axt1800-docker.config .config
                make defconfig

            #- name: Download package sources
             # run: make download V=s

            - name: Build tools
              run: |
                make tools/install -j$(nproc) V=s || \
                make tools/install V=s

            - name: Build toolchain
              run: |
                make toolchain/install -j$(nproc) V=s || \
                make toolchain/install V=s

            - name: Build target images
              run: |
                make -j$(nproc) V=s || \
                make V=s

            - name: TAR output
              run: tar -cvf ipq60xx-images.tar bin/targets/ipq60xx/generic

            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                name: ipq60xx-images
                path: ipq60xx-images.tar

    release:
          name: Make a release
          runs-on: ubuntu-latest
          needs: build

          steps:
            - name: Download the image artifacts
              uses: actions/download-artifact@v2
              with:
                name: ipq60xx-images

            - name: Extract the image artifacts
              run: tar xf ipq60xx-images.tar

            - name: Get the current date
              run: echo "NOW=$(date +%F-%H%M)" >> $GITHUB_ENV

            - name: Create a release
              uses: "lauravuo/action-automatic-releases@test-changes"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                prerelease: true
                title: "Updated prebuilt images ${{ env.NOW }}"
                automatic_release_tag: "ipq60xx-${{ env.NOW }}"
                auto_generate_release_notes: true
                files: bin/targets/ipq60xx/generic/*
