name: Sync Upstream Repos

on:
  push:
    branches:
      - actions
    paths:
      - .github/workflows/upstream.yaml
      - repos.yaml
      - sync.py
  workflow_dispatch:


env:
  TZ: Asia/Shanghai

jobs:
  upstream:
    runs-on: ubuntu-20.04

    steps:
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update
          sudo apt install git python3 python3-yaml

      - name: Checkout
        uses: actions/checkout@v3
        with: 
          token: ${{secrets.GH_TOKEN}}

      - name: Sync
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@github.com"
          python3 sync.py
